# The question text can be modified by the survey owner.
question: "Q1. 请填写下面的内容"
# The instructions to the question can be modified by the survey owner. It's recommended that the existing instructions are included in the customised instructions.
instruction: ""
# 这个是日期选择器,code不要随便改动,content可以改
options:
    [
        [
            { "code": "1", "content": "装卸投料" },
            { "code": "3", "content": "清洁工" },
            { "code": "4", "content": "管理" },
        ],
        [
            { "code": "a", "content": "定编人数" },
            { "code": "b", "content": "班次" },
            { "code": "c", "content": "备注" },
        ],
    ]

data: '{"a":{"type":"number"},"b":{"type":"eum","options":["早班","中班","晚班","临时工,没有固定工时(上下班打卡记录工作时长)"]},"c":{"type":"string"}}'
